CREATE TABLE IF NOT EXISTS POSTS_FROM_COMM2 AS
SELECT
	LINK_POST,
	COUNT(ID) AS NUM_COMMENTS,
	COUNT(DISTINCT(ID_AUTHOR)) AS NUM_AUTHORS,
	COUNT(APPEAL) AS COUNT_APPEAL,
	ROUND(AVG(LIKES), 3) AS AVG_COM_LIKES,
	ROUND(AVG(LENGTH), 3) AS AVG_COM_LENGTH,
	ROUND(100.0 * SUM(EXCLAMATION)/ SUM(LENGTH), 3) AS "%_COM_EXCLAMATION",
	ROUND(100.0 * SUM(QUESTION)/ SUM(LENGTH), 3) AS "%_COM_QUESTION",
	ROUND(100.0 * SUM(ELLIPSIS)/ SUM(LENGTH), 3) AS "%_COM_ELLIPSIS",
	ROUND(AVG(POSITIVITY), 3) AS AVG_POSITIVITY,
	ROUND(AVG(NEGATIVITY), 3) AS AVG_NEGATIVITY,
	ROUND(AVG(NEUTRALITY), 3) AS AVG_NEUTRALITY,
	ROUND(AVG(mins), 3) AS AVG_TIME_POST
FROM
	ALL_COMMS
GROUP BY 
	LINK_POST;